#!/bin/bash
SRC="$(pwd)/src"
FIRSTBOOT_SRC="${SRC}/firstboot"

# Logic Checks
if [ ! -x /usr/bin/xorriso ]; then
    echo "xorriso is not installed"
    exit 1
fi
if [ ! -x /usr/bin/patch ]; then
    echo "patch is not installed"
    exit 1
fi

# Argparse
OPTIND=1
while getopts d:p:v: opt
do
    case $opt in
        d)
            DEB_ISO=$(readlink -f ${OPTARG})
            ;;
        p)
            PRESEED_FILE=$(readlink -f ${OPTARG})
            ;;
        v)
            BUILD_VER=$OPTARG
            ;;
        *)
            exit 1
            ;;
    esac
done

if [ -z "${DEB_ISO}" ]; then
    echo "Missing '-d DEBIAN.iso'"
    exit 1
fi
if [ -z "${PRESEED_FILE}" ]; then
    echo "Missing '-p PRESEED_FILE'"
    exit 1
fi
if [ -z "${BUILD_VER}" ]; then
    echo "Missing '-v BUILD_VER'"
    exit 1
fi
if [ ! -f "${DEB_ISO}" ]; then
    echo "Debian ISO not found: ${DEB_ISO}"
    exit 1
fi
if [ ! -f "${PRESEED_FILE}" ]; then
    echo "Preseed file not found: ${PRESEED_FILE}"
    exit 1
fi
if [ ! -d "$(pwd)/src" ]; then
    echo "Script must be run from the project root directory"
    exit 1
fi
if [ -f "$(pwd)/asl-debian-installer-${BUILD_VER}.iso" ]; then
    echo "Move or delete $(pwd)/asl-debian-installer-${BUILD_VER}.iso"
    exit 1
fi

## Patch the initrd
patch_initrd() {
    local f=$1
    gunzip $f
    local unpacked="${f%.gz}"
    printf "preseed.cfg\nlate.sh" | cpio -H newc -o -A -F ${unpacked}
    gzip ${unpacked}
}

set -x
set -e

WORK_DIR=$(mktemp -d)
trap "rm -rf ${WORK_DIR}" EXIT

# Extract only the files we need to modify
xorriso -osirrox on -indev ${DEB_ISO} \
    -extract /boot/grub/grub.cfg    ${WORK_DIR}/grub.cfg \
    -extract /isolinux/drk.cfg      ${WORK_DIR}/drk.cfg \
    -extract /isolinux/drkgtk.cfg   ${WORK_DIR}/drkgtk.cfg \
    -extract /isolinux/gtk.cfg      ${WORK_DIR}/gtk.cfg \
    -extract /isolinux/menu.cfg     ${WORK_DIR}/menu.cfg \
    -extract /isolinux/spkgtk.cfg   ${WORK_DIR}/spkgtk.cfg \
    -extract /isolinux/txt.cfg      ${WORK_DIR}/txt.cfg \
    -extract /install.amd/initrd.gz ${WORK_DIR}/initrd.gz \
    -extract /install.amd/gtk/initrd.gz  ${WORK_DIR}/gtk-initrd.gz \
    -extract /install.amd/xen/initrd.gz  ${WORK_DIR}/xen-initrd.gz \
    --
chmod +w ${WORK_DIR}/*

## Update grub
patch ${WORK_DIR}/grub.cfg < ${SRC}/grub.patch

## Update isolinux
patch -p1 -d ${WORK_DIR} < ${SRC}/isolinux.patch

## Patch the initrd
cd ${WORK_DIR}
cp ${PRESEED_FILE} preseed.cfg
cp ${SRC}/late.sh late.sh
patch_initrd initrd.gz
patch_initrd gtk-initrd.gz
patch_initrd xen-initrd.gz
cd -

## Build the preseeded image by overlaying changes onto the original ISO
xorriso \
    -indev ${DEB_ISO} \
    -outdev $(pwd)/asl-debian-installer-${BUILD_VER}.iso \
    -volid "ASL Debian Installer" \
    -boot_image any replay \
    -map ${WORK_DIR}/grub.cfg       /boot/grub/grub.cfg \
    -map ${WORK_DIR}/grub.cfg       /boot/grub/x86_64-efi/grub.cfg \
    -map ${WORK_DIR}/grub.cfg       /EFI/debian/grub.cfg \
    -map ${WORK_DIR}/drk.cfg        /isolinux/drk.cfg \
    -map ${WORK_DIR}/drkgtk.cfg     /isolinux/drkgtk.cfg \
    -map ${WORK_DIR}/gtk.cfg        /isolinux/gtk.cfg \
    -map ${WORK_DIR}/menu.cfg       /isolinux/menu.cfg \
    -map ${WORK_DIR}/spkgtk.cfg     /isolinux/spkgtk.cfg \
    -map ${WORK_DIR}/txt.cfg        /isolinux/txt.cfg \
    -map ${WORK_DIR}/initrd.gz      /install.amd/initrd.gz \
    -map ${WORK_DIR}/gtk-initrd.gz      /install.amd/gtk/initrd.gz \
    -map ${WORK_DIR}/xen-initrd.gz      /install.amd/xen/initrd.gz \
    -map ${PRESEED_FILE}            /preseed.cfg \
    -map ${SRC}/post-install.sh     /post-install.sh \
    -map ${FIRSTBOOT_SRC}/          /asl3/ \
    -commit

