#!/bin/bash

SRC="$(pwd)/src"
FIRSTBOOT_SRC="${SRC}/firstboot"
ISO_SRC="$(pwd)/iso"


# Logic Checks
if [ ! -x /usr/bin/xorriso ]; then
	echo "xorriso is not installed"
	exit 1
fi

if [ ! -x /usr/bin/mcopy ]; then
	echo "mcopy/mtools is not installed"
	exit 1
fi

if [ ! -f /usr/lib/ISOLINUX/isohdpfx.bin ]; then
	echo "isolinux is not installed"
	exit 1
fi

if [ ! -x /usr/bin/patch ]; then
	echo "patch is not installed"
	exit 1
fi

# Argparse
OPTIND=1
while getopts d:p:v: opt
do
	case $opt in
		d)
			DEB_ISO=$OPTARG
			;;
		p)
			PRESEED_FILE=$OPTARG
			;;
		v)
			BUILD_VER=$OPTARG
			;;
		*)
			exit 1
			;;
	esac
done

if [ -z "${DEB_ISO}" ]; then
	echo "Missing '-d DEBIAN.iso'"
	exit 1
fi

if [ -z "${PRESEED_FILE}" ]; then
	echo "Missing '-v PRESEED_FILE'"
	exit 1
else
	PRESEED_FILE=$(readlink -f ${PRESEED_FILE})
fi

if [ -z "${BUILD_VER}" ]; then
	echo "Missing '-v BUILD_VER'"
	exit 1
fi

set -x
set -e

TMP_DIR=$(mktemp -d)

if [ ! -d ${ISO_SRC} ]; then
	mkdir ${ISO_SRC}
else
	chmod -R +w ${ISO_SRC}
	rm -rf ${ISO_SRC}
fi


# Unpack the ISO
xorriso -osirrox on -indev $DEB_ISO \
	 -extract / ${ISO_SRC}
cd ${ISO_SRC}

## Update Grub/EFI
chmod -R +w boot/grub EFI/debian
patch -p0 < ${SRC}/grub.patch
cp boot/grub/grub.cfg boot/grub/x86_64-efi/grub.cfg
cp boot/grub/grub.cfg EFI/debian/grub.cfg
mcopy -Do -i boot/grub/efi.img boot/grub/grub.cfg ::efi/debian/grub.cfg
mcopy -i boot/grub/efi.img ::efi/debian/grub.cfg /tmp/grub-efi-verify.cfg
sha256sum boot/grub/grub.cfg boot/grub/x86_64-efi/grub.cfg \
	EFI/debian/grub.cfg /tmp/grub-efi-verify.cfg
rm /tmp/grub-efi-verify.cfg
chmod -R -w boot/grub EFI/debian

## Update ISOLINUX
chmod -R +w isolinux/
patch -p0 < ${SRC}/isolinux.patch
chmod -R -w isolinux/

## Add preseed to the initrd
chmod -R +w install.amd/
cp ${PRESEED_FILE} preseed.cfg
cp ${SRC}/early.sh early.sh
cp ${SRC}/late.sh late.sh
find install.amd/ -name 'initrd.gz' -type f | while read f
do
	gunzip $f
	f=$(echo $f | sed 's/\.gz//g')
	echo preseed.cfg | cpio -H newc -o -A -F $f
	echo early.sh | cpio -H newc -o -A -F $f
	echo late.sh | cpio -H newc -o -A -F $f
	gzip $f
done
chmod -R -w install.amd/

## Stage our custom files
pwd
cp ${SRC}/post-install.sh .
chmod 755 post-install.sh
mkdir asl3
cp -r ${FIRSTBOOT_SRC} asl3/

## Regnerate the md5sum.txt
chmod +w md5sum.txt
find -follow -type f ! -name md5sum.txt -print0 | xargs -0 md5sum > md5sum.txt
chmod -w md5sum.txt

## Build the preseeded image
xorriso -as mkisofs \
    -r \
    -V "ASL Debian Installer" \
    -o ../asl-debian-installer-v$BUILD_VER.iso \
    -J -joliet-long \
    -cache-inodes \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -b isolinux/isolinux.bin \
      -no-emul-boot -boot-load-size 4 -boot-info-table \
    -eltorito-alt-boot \
    -e boot/grub/efi.img \
      -no-emul-boot \
    -isohybrid-gpt-basdat \
    .

## Cleanup
chmod -R +w ${ISO_SRC}
rm -rf ${ISO_SRC}